[workspace]

members = [
    "shared",
    "day1a",
    "day1b",
    "day2a",
    "day2b",
    "day3a",
    "day3b",
    "day5a",
    "day5b",
    "day19a",
    "day19b",
    "day20a",
    "day20b"
]
