[package]
name = "day5a"
version = "0.1.0"
edition = "2021"

[lib]
name = "day5a"
path = "src/lib.rs"

[[bin]]
name = "solve_day5a"
path = "src/main.rs"

[dependencies]
itertools = "0.12.0"
rayon = "1.8.0"
